const classtodos = [
  {
    id: 1,
    course: 'other',
    title: '程式設計',
    subTitle: '黃河銓',
    time: '1',
    hours: 3,
    credit: 3,
    content: '',
    completed: false,
    target:
      '本課程從基礎的python語法到物件導向程式設計(OOP)、名稱空間、例外處理、函數等，逐一介紹無遺。本課程將強調物件導向的觀念與程式撰寫技巧，同時輔 以簡潔且連貫的程式範例來呈現程式設計的精華。透過本課程，學生將可深植物件導向程式設計的觀念，並快速上手python程式設計。',
  },
  {
    id: 2,
    course: 'other',
    title: '基礎網頁設計',
    subTitle: '侯易佑',
    time: '1',
    hours: 3,
    credit: 3,
    completed: false,
    target:
      '本課程將由最基本的架站規劃開始，一步步帶領讀者了解JSP，達到建立JSP動態網站的目標。課程綱要包含了建置網站前的準備工作、基本軟體的安裝與設 定、 MySQL管理……等；Java與JSP程式設計篇則介紹JSP的語法，以及設計一些常用的函數；資料庫網頁篇包含了基本的SQL語法介紹，以及JSP與 MySQL結合的方法。',
  },
  {
    id: 3,
    course: 'other',
    title: '微積分(一)',
    subTitle: '黃天受',
    time: '1',
    hours: 3,
    credit: 3,
    completed: false,
    target:
      '1.訓練學生具備應有的數學解題能力\n2.培養學生思考研究的能力\n3.養成學生獨立解決問題的習慣。 ',
  },
  {
    id: 4,
    course: 'other',
    title: '經濟學',
    subTitle: '徐淑芳',
    time: '1',
    hours: 3,
    credit: 3,
    completed: false,
    target:
      '本課程主要探討財務管理議題(貨幣時間價值，投資組合，證券評價，投資決策, 風險管理, 洐生性金融商品等)的理論與實務',
  },
  {
    id: 5,
    course: 'other',
    title: '商業智慧導論',
    subTitle: '許瓊文',
    time: '1',
    hours: 3,
    credit: 3,
    completed: false,
    target: '概論  整合理論與實務的觀點瞭解E-coomerce，以期建立學生對E-coomerce的整體概念。',
  },
  {
    id: 6,
    course: 'other',
    title: '會計學',
    subTitle: '龔千芬',
    time: '1',
    hours: 3,
    credit: 3,
    completed: false,
    target: '1.培養學生思考研究的能力\n2.養成學生獨立解決問題的習慣。 ',
  },
  {
    id: 7,
    course: 'other',
    title: '程式設計(二)',
    subTitle: '謝文川',
    time: '2',
    hours: 3,
    credit: 3,
    completed: false,
    target:
      '本課程從基礎的python語法到物件導向程式設計(OOP)、名稱空間、例外處理、函數等，逐一介紹無遺。本課程將強調物件導向的觀念與程式撰寫技巧，同時輔 以簡潔且連貫的程式範例來呈現程式設計的精華。透過本課程，學生將可深植物件導向程式設計的觀念，並快速上手python程式設計。',
  },
  {
    id: 8,
    course: 'other',
    title: '微積分(二)',
    subTitle: '黃天受',
    time: '2',
    hours: 3,
    credit: 3,
    completed: false,
    target:
      '1.訓練學生具備應有的數學解題能力\n2.培養學生思考研究的能力\n3.養成學生獨立解決問題的習慣。',
  },
  {
    id: 9,
    course: 'other',
    title: 'Linux系統管理與應用',
    subTitle: '謝文川',
    time: '2',
    hours: 3,
    credit: 3,
    completed: false,
    target:
      '讓同學瞭解系統開發和系統分析與設計的基本觀念、原理，認識系統開發的五個主要階段（系統開發的生命週期模式）：系統規劃、系統需求分析、系統設計、系統 建置與測試、系統上線與維護等的實施重點 。進而引導同學學習系統分析與設計每個階段所使用的模式、工具與如何來進行的方法等。利用所學的工具和方法，進行實作練習，讓同學體驗系統開發的作業方 法。  ',
  },
  {
    id: 10,
    course: 'other',
    title: '伺服器端網頁設計',
    subTitle: '柯博昌',
    time: '2',
    hours: 3,
    credit: 3,
    completed: false,
    target:
      '本課程將由最基本的架站規劃開始，一步步帶領讀者了解JSP，達到建立JSP動態網站的目標。課程綱要包含了建置網站前的準備工作、基本軟體的安裝與設 定、 MySQL管理……等；Java與JSP程式設計篇則介紹JSP的語法，以及設計一些常用的函數；資料庫網頁篇包含了基本的SQL語法介紹，以及JSP與 MySQL結合的方法。   \n資料結構  本課程教導學生瞭解程式設計中各種資料結構的方法與相關演算法的使用。 ',
  },
  {
    id: 11,
    course: 'normal',
    title: 'Python程式設計',
    subTitle: '李仕雄',
    time: '2',
    hours: 3,
    credit: 3,
    completed: false,
    target:
      '本課程從基礎的python語法到物件導向程式設計(OOP)、名稱空間、例外處理、函數等，逐一介紹無遺。本課程將強調物件導向的觀念與程式撰寫技巧，同時輔 以簡潔且連貫的程式範例來呈現程式設計的精華。透過本課程，學生將可深植物件導向程式設計的觀念，並快速上手python程式設計。',
  },
  {
    id: 12,
    course: 'cloud',
    title: 'MVC系統架構',
    subTitle: '柯博昌',
    time: '3',
    hours: 3,
    credit: 3,
    completed: false,
    target:
      '本課程將由最基本的架站規劃開始，一步步帶領讀者了解JSP，達到建立JSP動態網站的目標。課程綱要包含了建置網站前的準備工作、基本軟體的安裝與設 定、 MySQL管理……等；Java與JSP程式設計篇則介紹JSP的語法，以及設計一些常用的函數；資料庫網頁篇包含了基本的SQL語法介紹，以及JSP與 MySQL結合的方法。   \n資料結構  本課程教導學生瞭解程式設計中各種資料結構的方法與相關演算法的使用。 ',
  },
  {
    id: 13,
    course: 'other',
    title: '資料庫管理',
    subTitle: '呂怡緯、傅振瑞',
    time: '3',
    hours: 3,
    credit: 3,
    completed: false,
    target: '關連式資料庫的理論與實務設計',
  },
  {
    id: 14,
    course: 'other',
    title: '程式設計(三)',
    subTitle: '呂怡緯、傅振瑞',
    time: '3',
    hours: 3,
    credit: 3,
    completed: false,
    target:
      '設計Java是屬於易學、易懂且跨平台的程式語言，在網際網路持續發展的今天，無論是J2SE、J2EE、J2ME或其他各個版本，網路程式的應用都是不可或 缺。其中 Java提供的物件在使用上相當便利，尤勝於其他程式語言。而這也意味了Java在高階語言尤其是網際網路的應用上，符合了開發時間短、可再用性高、成本 低廉…等優點。  ',
  },
  {
    id: 15,
    course: 'other',
    title: '人工智慧與深度學習',
    subTitle: '李仕雄',
    time: '3',
    hours: 3,
    credit: 3,
    completed: false,
    target: '尚無說明',
  },
  {
    id: 16,
    course: 'other',
    title: '統計學',
    subTitle: '徐淑芳',
    time: '3',
    hours: 3,
    credit: 3,
    completed: false,
    target:
      '本課程主要探討財務管理議題(貨幣時間價值，投資組合，證券評價，投資決策, 風險管理, 洐生性金融商品等)的理論與實務。此外，訓練學生能運用資訊技術(電腦語言)自行撰寫上述財務相關的程式。目標是:　 ',
  },
  {
    id: 17,
    course: 'normal',
    title: '投資決策與應用',
    subTitle: '徐淑芳',
    time: '3',
    hours: 3,
    credit: 3,
    completed: false,
    target:
      '本課程主要探討財務管理議題(貨幣時間價值，投資組合，證券評價，投資決策, 風險管理, 洐生性金融商品等)的理論與實務。此外，訓練學生能運用資訊技術(電腦語言)自行撰寫上述財務相關的程式。目標是:\n1.了解資訊技術在金融機構或企業所扮演的角色。\n2.瞭解資訊技術在金融機構中的重要性\n3.如何再提昇一數位化金融機構之管理。　 ',
  },
  {
    id: 18,
    course: 'normal',
    title: '資料模型',
    subTitle: '???',
    time: '3',
    hours: 3,
    credit: 3,
    completed: false,
    target: '建立學生生產與作業的基本觀念及技巧，培養學生管理概念，結合未來工作實務。 ',
  },
  {
    id: 19,
    course: 'normal',
    title: '行銷管理',
    subTitle: '???',
    time: '3',
    hours: 3,
    credit: 3,
    completed: false,
    target:
      'As an integrative course, with case studies and fieldwork, much of the learning is dependent on accessing the combined knowledge and experience of the group. It is everyones job to keep the discussion productive and moving forward. In class discussions it is equally as important to talk about how to do something as what to do.',
  },
  {
    id: 20,
    course: 'other',
    title: '資料分析與統計',
    subTitle: '張添香',
    time: '4',
    hours: 3,
    credit: 3,
    completed: false,
    target:
      '本課程主要探討財務管理議題(貨幣時間價值，投資組合，證券評價，投資決策, 風險管理, 洐生性金融商品等)的理論與實務。此外，訓練學生能運用資訊技術(電腦語言)自行撰寫上述財務相關的程式。目標是:\n1.了解資訊技術在金融機構或企業所扮演的角色。\n2.瞭解資訊技術在金融機構中的重要性\n3.如何再提昇一數位化金融機構之管理。　 ',
  },
  {
    id: 21,
    course: 'other',
    title: '系統分析與設計',
    subTitle: '呂怡緯、傅振瑞',
    time: '4',
    hours: 3,
    credit: 3,
    completed: false,
    target:
      '讓同學瞭解系統開發和系統分析與設計的基本觀念、原理，認識系統開發的五個主要階段（系統開發的生命週期模式）：系統規劃、系統需求分析、系統設計、系統 建置與測試、系統上線與維護等的實施重點 。進而引導同學學習系統分析與設計每個階段所使用的模式、工具與如何來進行的方法等。利用所學的工具和方法，進行實作練習，讓同學體驗系統開發的作業方 法。  ',
  },
  {
    id: 22,
    course: 'other',
    title: '機器學習應用',
    subTitle: '龔千芬',
    time: '4',
    hours: 3,
    credit: 3,
    completed: false,
    target: '尚無說明',
  },
  {
    id: 23,
    course: 'marketing',
    title: '商業智慧',
    subTitle: '許瓊文',
    time: '4',
    hours: 3,
    credit: 3,
    completed: false,
    target: '概論  整合理論與實務的觀點瞭解E-coomerce，以期建立學生對E-coomerce的整體概念。 ',
  },
  {
    id: 24,
    course: 'cloud',
    title: '前端網頁框架',
    subTitle: '呂怡緯',
    time: '4',
    hours: 3,
    credit: 3,
    completed: false,
    target:
      '本課程將由最基本的架站規劃開始，一步步帶領讀者了解react，達到建立react動態網站的目標。課程綱要包含了建置網站前的準備工作、基本軟體的安裝與設 定、 MySQL管理……等；react-native程式設計篇則介紹react-native的語法，以及設計一些常用的函數；資料庫網頁篇包含了基本的SQL語法介紹，以及react-native與 MySQL結合的方法。   \n資料結構  本課程教導學生瞭解程式設計中各種資料結構的方法與相關演算法的使用。 ',
  },
  {
    id: 25,
    course: 'ai',
    title: '感測器與物聯網實作',
    subTitle: '李仕雄',
    time: '4',
    hours: 3,
    credit: 3,
    completed: false,
    target: '尚無說明',
  },
  {
    id: 26,
    course: 'bigdata',
    title: '程式交易實作',
    subTitle: '酆士昌、林萍珍',
    time: '4',
    hours: 3,
    credit: 3,
    completed: false,
    target:
      '本課程主要探討財務管理議題(貨幣時間價值，投資組合，證券評價，投資決策, 風險管理, 洐生性金融商品等)的理論與實務。此外，訓練學生能運用資訊技術(電腦語言)自行撰寫上述財務相關的程式。目標是:\n1.了解資訊技術在金融機構或企業所扮演的角色。\n2.瞭解資訊技術在金融機構中的重要性\n3.如何再提昇一數位化金融機構之管理。　 ',
  },
  {
    id: 27,
    course: 'normal',
    title: '電子商務與網路拍賣',
    subTitle: '???',
    time: '4',
    hours: 3,
    credit: 3,
    completed: false,
    target: '概論  整合理論與實務的觀點瞭解E-coomerce，以期建立學生對E-coomerce的整體概念。 ',
  },
  {
    id: 28,
    course: 'normal',
    title: '管理數學',
    subTitle: '???',
    time: '4',
    hours: 3,
    credit: 3,
    completed: false,
    target:
      '1.訓練學生具備應有的數學解題能力\n2.培養學生思考研究的能力\n3.養成學生獨立解決問題的習慣。 ',
  },
  {
    id: 29,
    course: 'normal',
    title: '多媒體視覺設計',
    subTitle: '???',
    time: '4',
    hours: 3,
    credit: 3,
    completed: false,
    target: '尚無說明',
  },
  {
    id: 30,
    course: 'other',
    title: '商務資訊系統',
    subTitle: '張俊陽',
    time: '5',
    hours: 3,
    credit: 3,
    completed: false,
    target:
      ' 本課程的目的，就是從管理的角度來幫助學生熟悉企業應用資訊管理的基本原理。 主要上課方式為課堂講解,配合每章最後的案例進行研討 ',
  },
  {
    id: 31,
    course: 'marketing',
    title: '智慧商務平台規劃與設計',
    subTitle: '許瓊文',
    time: '5',
    hours: 3,
    credit: 3,
    completed: false,
    target: '概論  整合理論與實務的觀點瞭解E-coomerce，以期建立學生對E-coomerce的整體概念。 ',
  },
  {
    id: 32,
    course: 'marketing',
    title: 'APP程式開發與設計',
    subTitle: '蔡家斌',
    time: '5',
    hours: 3,
    credit: 3,
    completed: false,
    target:
      '本課程將由最基本的架站規劃開始，一步步帶領讀者了解react，達到建立react動態網站的目標。課程綱要包含了建置網站前的準備工作、基本軟體的安裝與設 定、 MySQL管理……等；react-native程式設計篇則介紹react-native的語法，以及設計一些常用的函數；資料庫網頁篇包含了基本的SQL語法介紹，以及react-native與 MySQL結合的方法。   \n資料結構  本課程教導學生瞭解程式設計中各種資料結構的方法與相關演算法的使用。',
  },
  {
    id: 33,
    course: 'cloud',
    title: 'APP程式開發與設計',
    subTitle: '蔡家斌',
    time: '5',
    hours: 3,
    credit: 3,
    completed: false,
    target:
      '本課程將由最基本的架站規劃開始，一步步帶領讀者了解react，達到建立react動態網站的目標。課程綱要包含了建置網站前的準備工作、基本軟體的安裝與設 定、 MySQL管理……等；react-native程式設計篇則介紹react-native的語法，以及設計一些常用的函數；資料庫網頁篇包含了基本的SQL語法介紹，以及react-native與 MySQL結合的方法。   \n資料結構  本課程教導學生瞭解程式設計中各種資料結構的方法與相關演算法的使用。',
  },
  {
    id: 34,
    course: 'ai',
    title: '智聯網系統設計與應用實務',
    subTitle: '李仕雄',
    time: '5',
    hours: 3,
    credit: 3,
    completed: false,
    target: '尚無說明',
  },
  {
    id: 35,
    course: 'bigdata',
    title: '大數據分析與實作',
    subTitle: '龔千芬',
    time: '5',
    hours: 3,
    credit: 3,
    completed: false,
    target: '尚無說明',
  },
  {
    id: 36,
    course: 'normal',
    title: '英文口語訓練',
    subTitle: '???',
    time: '5',
    hours: 3,
    credit: 3,
    completed: false,
    target: '尚無說明',
  },
  {
    id: 37,
    course: 'normal',
    title: '智慧製造',
    subTitle: '???',
    time: '5',
    hours: 3,
    credit: 3,
    completed: false,
    target: '建立學生生產與作業的基本觀念及技巧，培養學生管理概念，結合未來工作實務。',
  },
  {
    id: 38,
    course: 'normal',
    title: '電子化流程設計與管理',
    subTitle: '???',
    time: '5',
    hours: 3,
    credit: 3,
    completed: false,
    target: '建立學生生產與作業的基本觀念及技巧，培養學生管理概念，結合未來工作實務。',
  },
  {
    id: 39,
    course: 'other',
    title: '大數據商業分析與決策',
    subTitle: '???',
    time: '6',
    hours: 3,
    credit: 3,
    completed: false,
    target: '尚無說明',
  },
  {
    id: 40,
    course: 'other',
    title: '實務專題(一)',
    subTitle: '???',
    time: '6',
    hours: 3,
    credit: 1,
    completed: false,
    target: '尚無說明',
  },
  {
    id: 41,
    course: 'marketing',
    title: '社群行銷與口碑分析',
    subTitle: '許瓊文',
    time: '6',
    hours: 3,
    credit: 3,
    completed: false,
    target:
      'As an integrative course, with case studies and fieldwork, much of the learning is dependent on accessing the combined knowledge and experience of the group. It is everyones job to keep the discussion productive and moving forward. In class discussions it is equally as important to talk about how to do something as what to do.',
  },
  {
    id: 42,
    course: 'cloud',
    title: '智慧雲端商務專題',
    subTitle: '???',
    time: '6',
    hours: 3,
    credit: 3,
    completed: false,
    target: '尚無說明',
  },
  {
    id: 43,
    course: 'ai',
    title: '應用服務與物聯網實作',
    subTitle: '???',
    time: '6',
    hours: 3,
    credit: 3,
    completed: false,
    target: '尚無說明',
  },
  {
    id: 44,
    course: 'bigdata',
    title: '金融科技企劃與實作',
    subTitle: '???',
    time: '6',
    hours: 3,
    credit: 3,
    completed: false,
    target:
      '本課程主要探討財務管理議題(貨幣時間價值，投資組合，證券評價，投資決策, 風險管理, 洐生性金融商品等)的理論與實務。此外，訓練學生能運用資訊技術(電腦語言)自行撰寫上述財務相關的程式。目標是:\n1.了解資訊技術在金融機構或企業所扮演的角色。\n2.瞭解資訊技術在金融機構中的重要性\n3.如何再提昇一數位化金融機構之管理。　 ',
  },
  {
    id: 45,
    course: 'normal',
    title: '暑期實習',
    subTitle: '???',
    time: '6',
    hours: 2,
    credit: 2,
    completed: false,
    target: '尚無說明',
  },
  {
    id: 46,
    course: 'normal',
    title: '專案實習',
    subTitle: '???',
    time: '6',
    hours: 2,
    credit: 2,
    completed: false,
    target: '尚無說明',
  },
  {
    id: 47,
    course: 'normal',
    title: '進階英語口語訓練',
    subTitle: '???',
    time: '6',
    hours: 3,
    credit: 3,
    completed: false,
    target: '尚無說明',
  },
  {
    id: 48,
    course: 'normal',
    title: '人工智慧與學習科技',
    subTitle: '???',
    time: '6',
    hours: 3,
    credit: 3,
    completed: false,
    target: '尚無說明',
  },
  {
    id: 49,
    course: 'normal',
    title: 'ASPNET應用程式開發與設計',
    subTitle: '???',
    time: '6',
    hours: 3,
    credit: 3,
    completed: false,
    target: '尚無說明',
  },
  {
    id: 50,
    course: 'normal',
    title: '財務管理',
    subTitle: '???',
    time: '6',
    hours: 3,
    credit: 3,
    completed: false,
    target:
      '本課程主要探討財務管理議題(貨幣時間價值，投資組合，證券評價，投資決策, 風險管理, 洐生性金融商品等)的理論與實務。此外，訓練學生能運用資訊技術(電腦語言)自行撰寫上述財務相關的程式。目標是:\n1.了解資訊技術在金融機構或企業所扮演的角色。\n2.瞭解資訊技術在金融機構中的重要性\n3.如何再提昇一數位化金融機構之管理。　 ',
  },
  {
    id: 51,
    course: 'other',
    title: '實務專題(二)',
    subTitle: '???',
    time: '7',
    hours: 1,
    credit: 3,
    completed: false,
    target: '尚無說明',
  },
  {
    id: 52,
    course: 'marketing',
    title: '智慧行銷應用專題',
    subTitle: '???',
    time: '7',
    hours: 3,
    credit: 3,
    completed: false,
    target:
      'As an integrative course, with case studies and fieldwork, much of the learning is dependent on accessing the combined knowledge and experience of the group. It is everyones job to keep the discussion productive and moving forward. In class discussions it is equally as important to talk about how to do something as what to do.',
  },
  {
    id: 53,
    course: 'ai',
    title: '智聯網創新應用專題',
    subTitle: '???',
    time: '7',
    hours: 3,
    credit: 3,
    completed: false,
    target:
      '本課程主要探討財務管理議題(貨幣時間價值，投資組合，證券評價，投資決策, 風險管理, 洐生性金融商品等)的理論與實務。此外，訓練學生能運用資訊技術(電腦語言)自行撰寫上述財務相關的程式。目標是:\n1.了解資訊技術在金融機構或企業所扮演的角色。\n2.瞭解資訊技術在金融機構中的重要性\n3.如何再提昇一數位化金融機構之管理。　 ',
  },
  {
    id: 54,
    course: 'bigdata',
    title: '智慧金融應用專題',
    subTitle: '???',
    time: '7',
    hours: 3,
    credit: 3,
    completed: false,
    target:
      '本課程主要探討財務管理議題(貨幣時間價值，投資組合，證券評價，投資決策, 風險管理, 洐生性金融商品等)的理論與實務。此外，訓練學生能運用資訊技術(電腦語言)自行撰寫上述財務相關的程式。目標是:\n1.了解資訊技術在金融機構或企業所扮演的角色。\n2.瞭解資訊技術在金融機構中的重要性\n3.如何再提昇一數位化金融機構之管理。　 ',
  },
  {
    id: 55,
    course: 'normal',
    title: '學期實習',
    subTitle: '???',
    time: '7',
    hours: 9,
    credit: 9,
    completed: false,
    target: '尚無說明',
  },
  {
    id: 56,
    course: 'normal',
    title: '學年實習',
    subTitle: '???',
    time: '7',
    hours: 18,
    credit: 18,
    completed: false,
    target: '尚無說明',
  },
  {
    id: 57,
    course: 'normal',
    title: '創客與創業實務專題',
    subTitle: '???',
    time: '7',
    hours: 3,
    credit: 3,
    completed: false,
    target: '尚無說明',
  },
  {
    id: 58,
    course: 'normal',
    title: '物流大數據',
    subTitle: '???',
    time: '7',
    hours: 3,
    credit: 3,
    completed: false,
    target: '尚無說明',
  },
  {
    id: 59,
    course: 'normal',
    title: 'NOSQL非關聯式資料庫',
    subTitle: '???',
    time: '7',
    hours: 3,
    credit: 3,
    completed: false,
    target:
      '1.Basic Concepts\n2.Physical Design\n3.Relational Algebra\n4.SQL\n5.Data Warehousing\n6.Data and Database Administration\n7.專題報告',
  },
  {
    id: 60,
    course: 'normal',
    title: '專案管理',
    subTitle: '???',
    time: '8',
    hours: 3,
    credit: 3,
    completed: false,
    target: '尚無說明',
  },
  {
    id: 61,
    course: 'normal',
    title: '資料探勘',
    subTitle: '???',
    time: '8',
    hours: 3,
    credit: 3,
    completed: false,
    target: '尚無說明',
  },
  {
    id: 62,
    course: 'normal',
    title: '智慧倉儲管理',
    subTitle: '???',
    time: '8',
    hours: 3,
    credit: 3,
    completed: false,
    target: '建立學生生產與作業的基本觀念及技巧，培養學生管理概念，結合未來工作實務。 ',
  },
  {
    id: 63,
    course: 'normal',
    title: '數位行銷整合實務',
    subTitle: '???',
    time: '8',
    hours: 3,
    credit: 3,
    completed: false,
    target: '尚無說明',
  },
  {
    id: 64,
    course: 'normal',
    title: '資料倉儲與線上分析',
    subTitle: '???',
    time: '8',
    hours: 3,
    credit: 3,
    completed: false,
    target:
      '1.Basic Concepts\n2.Physical Design\n3.Relational Algebra\n4.SQL\n5.Data Warehousing\n6.Data and Database Administration\n7.專題報告',
  },
];
export default classtodos;
